//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSThemeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSMSThemeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSMS Theme Editor.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlankImage {
            get {
                object obj = ResourceManager.GetObject("BlankImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body { font-family:Consolas; font-size:11pt; }
        ///        /*&lt;&lt;CSS&gt;&gt;*/
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;pre&gt;
        ///    &lt;span class=&quot;Keyword&quot;&gt;USE&lt;/span&gt; &lt;span class=&quot;Identifier&quot;&gt;AdventureWorks2012&lt;/span&gt;;
        ///    &lt;span class=&quot;Keyword&quot;&gt;GO&lt;/span&gt;
        ///
        ///    &lt;span class=&quot;Comment&quot;&gt;/*----------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLSample {
            get {
                return ResourceManager.GetString("SQLSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserSettings&gt;
        ///	&lt;ApplicationIdentity version=&quot;10.0&quot;/&gt;
        ///	&lt;ToolsOptions&gt;
        ///		&lt;ToolsOptionsCategory name=&quot;Environment&quot; RegisteredName=&quot;Environment&quot;/&gt;
        ///	&lt;/ToolsOptions&gt;
        ///	&lt;Category name=&quot;Environment_Group&quot; RegisteredName=&quot;Environment_Group&quot;&gt;
        ///		&lt;Category name=&quot;Environment_FontsAndColors&quot; Category=&quot;{1EDA5DD4-927A-43a7-810E-7FD247D0DA1D}&quot; Package=&quot;{DA9FB551-C724-11d0-AE1F-00A0C90FFFC3}&quot; RegisteredName=&quot;Environment_FontsAndColors&quot; PackageName=&quot;Visual Studio Environment Package&quot;&gt;
        ///			&lt;PropertyValue name=&quot;Version&quot;&gt;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VSSettingsTemplate {
            get {
                return ResourceManager.GetString("VSSettingsTemplate", resourceCulture);
            }
        }
    }
}
